---@class NRSKNUI
local NRSKNUI = select(2, ...)

-- Auto Generated Dungeon Timer Presets
-- Pasted into DungeonTimerPresets.lua

NRSKNUI.DungeonTimerPresets = {
    _version = 1,

    -- Pit of Saron (instanceId 658)
    PitOfSaron = {
        Triggers = {
            [1] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 1,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1261546",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [2] = {
                actionOnHideSound = "\124cfff900ffFind Safespot\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 2,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Safespot",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1262029",
                textColor = {
                    0,
                    1,
                    0.96862751245499,
                    1,
                },
                textFormat = "SAFESPOT » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [3] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 3,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B2 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1264287",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [4] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit + Knockback",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 4,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B3 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1262582",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [5] = {
                actionOnHideSound = "\124cfff900ffAdds\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 5,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B3 Adds",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1263406",
                textColor = {
                    1,
                    0.53333336114883,
                    0.96862751245499,
                    1,
                },
                textFormat = "ADDS » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [6] = {
                actionOnHideSound = "\124cfff900ffDebuffs\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 6,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B3 Debuffs",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1262745",
                textColor = {
                    0,
                    1,
                    0.90980398654938,
                    1,
                },
                textFormat = "DEBUFFS » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
        },
    },

    -- Nexus-Point Xenas (instanceId 2915)
    NexusPointXenas = {
        Triggers = {
            [1] = {
                actionOnHideSound = "\124cfff900ffKnockback\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = false,
                extendTimer = 0,
                id = 1,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Knockback",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1257509",
                textColor = {
                    1,
                    0,
                    1,
                    1,
                },
                textFormat = "KNOCKBACK » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [2] = {
                actionOnHideSound = "Details Gun2",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.77254909276962,
                    0.16862745583057,
                    0.16862745583057,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                decimalThreshold = 3,
                displayType = "bar",
                enabled = true,
                id = 2,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = false,
                message = "",
                messageOperator = "find",
                name = "B2 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                showDecimals = false,
                spellId = "1247937",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "Tank Hit %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [3] = {
                actionOnHideSound = "\124cfff900ffAdds\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 3,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B2 Adds",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1252703",
                textColor = {
                    1,
                    0,
                    0.58039218187332,
                    1,
                },
                textFormat = "ADDS » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [4] = {
                actionOnHideSound = "\124cfff900ffDmg Amp\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 4,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B2 Dmg Amp",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1264439",
                textColor = {
                    1,
                    0.80000007152557,
                    0,
                    1,
                },
                textFormat = "DMG AMP » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [5] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.77254909276962,
                    0.16862745583057,
                    0.16862745583057,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 3,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 5,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B3 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = false,
                spellId = "1253950",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "Tank Hit %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [6] = {
                actionOnHideSound = "\124cfff900ffIntermission\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 6,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B3 Intermission",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1257595",
                textColor = {
                    0,
                    0.96078437566757,
                    1,
                    1,
                },
                textFormat = "INTERMISSION » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
        },
    },

    -- Skyreach (instanceId 1209)
    Skyreach = {
        Triggers = {
            [1] = {
                actionOnHideSound = "\124cfff900ffDebuffs\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "",
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 1,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Debuffs",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "153757",
                textColor = {
                    1,
                    0.34117648005486,
                    0,
                    1,
                },
                textFormat = "DEBUFFS » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [2] = {
                actionOnHideSound = "\124cfff900ffTornadoes\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "",
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 2,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Tornadoes",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "156793",
                textColor = {
                    0,
                    1,
                    0.98039221763611,
                    1,
                },
                textFormat = "TORNADOES » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [3] = {
                actionOnHideSound = "None",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    1,
                    0.85882359743118,
                    0,
                    1,
                },
                barText1Format = "Frontal",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "",
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 3,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B2 Frontal",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "154110",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [4] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.77254909276962,
                    0.16862745583057,
                    0.16862745583057,
                    1,
                },
                barText1Format = "Tank Hit + Bleed",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "",
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 4,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B3 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1253519",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [5] = {
                actionOnHideSound = "\124cfff900ffAdds\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "",
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 5,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B3 Add",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1253510",
                textColor = {
                    1,
                    0.61960786581039,
                    0,
                    1,
                },
                textFormat = "ADD » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [6] = {
                actionOnHideSound = "\124cfff900ffFind Safespot\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "",
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 6,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B3 Find Safespot",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "159382",
                textColor = {
                    1,
                    0,
                    0.30196079611778,
                    1,
                },
                textFormat = "FIND SAFESPOT » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [7] = {
                actionOnHideSound = "\124cfff900ffBeam\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "",
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 7,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B4 Beam",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1253840",
                textColor = {
                    0,
                    1,
                    0.89803928136826,
                    1,
                },
                textFormat = "BEAM » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [8] = {
                actionOnHideSound = "\124cfff900ffAdds\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "",
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 8,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B4 Add",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "153954",
                textColor = {
                    0,
                    1,
                    0.56078433990479,
                    1,
                },
                textFormat = "ADD » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
        },
    },

    -- Seat of the Triumvirate (instanceId 1753)
    SeatOfTriumvirate = {
        Triggers = {
            [1] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 1,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1263440",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [2] = {
                actionOnHideSound = "\124cfff900ffPull\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 2,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Pull",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1263297",
                textColor = {
                    0,
                    0.83921575546265,
                    1,
                    1,
                },
                textFormat = "PULL » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [3] = {
                actionOnHideSound = "\124cfff900ffFrontal\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 3,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Frontal",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1268916",
                textColor = {
                    1,
                    0,
                    0.98039221763611,
                    1,
                },
                textFormat = "FRONTAL » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [4] = {
                actionOnHideSound = "\124cfff900ffAdds\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 4,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Adds",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1263399",
                textColor = {
                    0,
                    0.72156864404678,
                    1,
                    1,
                },
                textFormat = "ADDS » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [5] = {
                actionOnHideSound = "None",
                actionOnShowSound = "\124cfff900ffBait\124r",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 5,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B2 Bait",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1248219",
                textColor = {
                    0.98039221763611,
                    0,
                    1,
                    1,
                },
                textFormat = "BAIT » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [6] = {
                actionOnHideSound = "None",
                actionOnShowSound = "\124cfff900ffPre-Spread\124r",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 6,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B2 Spread",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 3,
                showDecimals = true,
                spellId = "1280065",
                textColor = {
                    1,
                    0,
                    0.7607843875885,
                    1,
                },
                textFormat = "PRE-SPREAD » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
        },
    },

    -- Algeth'ar Academy (instanceId 2526)
    AlgetharAcademy = {
        Triggers = {
            [1] = {
                Position = {
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    XOffset = 0,
                    YOffset = 105,
                },
                actionOnHideSound = "Details Gun2",
                backgroundColor = {
                    0,
                    0,
                    0,
                    0.80000001192093,
                },
                barColor = {
                    1,
                    0.85882359743118,
                    0,
                    1,
                },
                barHeight = 24,
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                barWidth = 220,
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                fontSize = 14,
                iconEnabled = true,
                id = 1,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "385958",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "TANK HIT » %p",
                textJustify = "CENTER",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [2] = {
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.2,
                    0.6,
                    1,
                    1,
                },
                barText1Format = "%n",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "function()\n  local text = \"\124T1405803:12\124t\"\n  return text\nend",
                customTextFunc = "function()\n  local text = '\124cff66ff00'..'+'..\"200\"..'%'..'\124r'\n  return text\nend\n\n\n",
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 2,
                loadRoleDPS = false,
                loadRoleEnabled = false,
                loadRoleHealer = false,
                loadRoleTank = false,
                message = "",
                messageOperator = "find",
                name = "B1 Aoe",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "388537",
                textColor = {
                    1,
                    0,
                    0.83921575546265,
                    1,
                },
                textFormat = "AOE » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [5] = {
                Position = {
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    XOffset = 0,
                    YOffset = 105,
                },
                actionOnHideSound = "Details Gun2",
                backgroundColor = {
                    0,
                    0,
                    0,
                    0.80000001192093,
                },
                barColor = {
                    0.77254909276962,
                    0.16862745583057,
                    0.16862745583057,
                    1,
                },
                barHeight = 24,
                barText1Format = "Tank Hit",
                barText1XOffset = 3,
                barText2Format = "%p",
                barText2XOffset = -3,
                barWidth = 220,
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                fontSize = 14,
                iconEnabled = true,
                id = 5,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B2 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "388544",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "TANK HIT » %p",
                textJustify = "CENTER",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [6] = {
                actionOnHideSound = "\124cfff900ffAoe\124r",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.2,
                    0.6,
                    1,
                    1,
                },
                barText1Format = "%n",
                barText1Justify = "LEFT",
                barText1XOffset = 4,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -4,
                barText2YOffset = 0,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                id = 6,
                loadRoleDPS = false,
                loadRoleEnabled = false,
                loadRoleHealer = false,
                loadRoleTank = false,
                message = "",
                messageOperator = "find",
                name = "B2 Aoe",
                remainingEnabled = true,
                remainingOperator = "<=",
                showDecimals = true,
                spellId = "388923",
                textColor = {
                    1,
                    0.60000002384186,
                    0,
                    1,
                },
                textFormat = "AOE » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [7] = {
                Position = {
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    XOffset = 0,
                    YOffset = 0,
                },
                actionOnHideSound = "None",
                actionOnShowSound = "\124cfff900ffStack\124r",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.2,
                    0.6,
                    1,
                    1,
                },
                barText1Format = "%n",
                barText1Justify = "LEFT",
                barText1XOffset = 4,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -4,
                barText2YOffset = 0,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 7,
                loadRoleDPS = false,
                loadRoleEnabled = false,
                loadRoleHealer = false,
                loadRoleTank = false,
                message = "",
                messageOperator = "find",
                name = "B2 Stack",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 3,
                showDecimals = true,
                spellId = "388796",
                textColor = {
                    0.1803921610117,
                    1,
                    0,
                    1,
                },
                textFormat = "STACK » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [8] = {
                Position = {
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    XOffset = 0,
                    YOffset = 105,
                },
                actionOnHideSound = "Details Gun2",
                backgroundColor = {
                    0,
                    0,
                    0,
                    0.80000001192093,
                },
                barColor = {
                    0.77254909276962,
                    0.16862745583057,
                    0.16862745583057,
                    1,
                },
                barHeight = 24,
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                barWidth = 220,
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                fontSize = 14,
                iconEnabled = true,
                id = 8,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B3 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "376997",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "TANK HIT » %p",
                textJustify = "CENTER",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [9] = {
                actionOnHideSound = "\124cfff900ffAoe\124r",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.2,
                    0.6,
                    1,
                    1,
                },
                barText1Format = "%n",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 9,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = false,
                message = "",
                messageOperator = "find",
                name = "B3 Aoe",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "377004",
                textColor = {
                    1,
                    0.96078437566757,
                    0,
                    1,
                },
                textFormat = "AOE » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [10] = {
                Position = {
                    AnchorFrom = "CENTER",
                    AnchorTo = "CENTER",
                    XOffset = 0,
                    YOffset = 105,
                },
                actionOnHideSound = "Details Gun2",
                backgroundColor = {
                    0,
                    0,
                    0,
                    0.80000001192093,
                },
                barColor = {
                    0.77254909276962,
                    0.16862745583057,
                    0.16862745583057,
                    1,
                },
                barHeight = 24,
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                barWidth = 220,
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                fontSize = 14,
                iconEnabled = true,
                id = 10,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B4 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1282251",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "TANK HIT » %p",
                textJustify = "CENTER",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [11] = {
                actionOnHideSound = "\124cfff900ffPull\124r",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.2,
                    0.6,
                    1,
                    1,
                },
                barText1Format = "%n",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 11,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B4 Pull",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "388822",
                textColor = {
                    0.85882359743118,
                    0,
                    1,
                    1,
                },
                textFormat = "PULL » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
        },
    },

    -- Maisara Caverns (instanceId 2874)
    MaisaraCaverns = {
        Triggers = {
            [1] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 1,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1266480",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [2] = {
                actionOnHideSound = "\124cfff900ffCharge\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 2,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Charge",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1249479",
                textColor = {
                    0.61960786581039,
                    1,
                    0,
                    1,
                },
                textFormat = "CHARGE » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [3] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 3,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B2 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1251554",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [4] = {
                actionOnHideSound = "\124cfff900ffFrontal\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 4,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B2 Frontal",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1252054",
                textColor = {
                    0,
                    1,
                    0.72156864404678,
                    1,
                },
                textFormat = "FRONTAL » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [5] = {
                actionOnHideSound = "\124cfff900ffIntermission\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 5,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B2 Intermission",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1250708",
                textColor = {
                    0,
                    1,
                    0.49803924560547,
                    1,
                },
                textFormat = "INTERMISSION » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [6] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit + Knock",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 6,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B3 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1251023",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [7] = {
                actionOnHideSound = "\124cfff900ffIntermission\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 7,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B3 Intermission",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1253788",
                textColor = {
                    1,
                    0.27843138575554,
                    0,
                    1,
                },
                textFormat = "INTERMISSION » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
        },
    },

    -- Magisters' Terrace (instanceId 2811)
    MagistersTerrace = {
        Triggers = {
            [1] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit + Knock",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 1,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "474496",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [2] = {
                actionOnHideSound = "\124cfff900ffKnockback\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "\n\n",
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 2,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Knockback",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1214081",
                textColor = {
                    0.86274516582489,
                    0,
                    1,
                    1,
                },
                textFormat = "KNOCKBACK » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [3] = {
                actionOnHideSound = "\124cfff900ffIntermission\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 3,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Intermission",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "474345",
                textColor = {
                    0,
                    0.81960791349411,
                    1,
                    1,
                },
                textFormat = "INTERMISSION » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [4] = {
                actionOnHideSound = "\124cfff900ffDebuffs\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 4,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B2 Debuffs",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1225787",
                textColor = {
                    0.96078437566757,
                    0,
                    1,
                    1,
                },
                textFormat = "DEBUFFS » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [5] = {
                actionOnHideSound = "\124cfff900ffAbsorbs\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 5,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B3 Mob Absorbs",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1253709",
                textColor = {
                    0.96078437566757,
                    0,
                    1,
                    1,
                },
                textFormat = "BOSS ABSORB » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [6] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Debuff",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 6,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B4 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "1280113",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
        },
    },

    -- Windrunner Spire (instanceId 2805)
    WindrunnerSpire = {
        Triggers = {
            [1] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "",
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 1,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "466064",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [2] = {
                actionOnHideSound = "\124cfff900ffIntermission\124r",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "",
                decimalThreshold = 1,
                displayType = "text",
                enabled = true,
                extendTimer = 0,
                id = 2,
                loadRoleDPS = true,
                loadRoleEnabled = false,
                loadRoleHealer = true,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B1 Intermission",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "465904",
                textColor = {
                    1,
                    0.49803924560547,
                    0,
                    1,
                },
                textFormat = "INTERMISSION » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = true,
            },
            [3] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "",
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 3,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B2 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "472888",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [4] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "",
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 4,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B3 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "467620",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
            [5] = {
                actionOnHideSound = "Details Gun2",
                actionOnShowSound = "None",
                backgroundColor = {
                    0.1,
                    0.1,
                    0.1,
                    0.8,
                },
                barColor = {
                    0.772,
                    0.168,
                    0.168,
                    1,
                },
                barText1Format = "Tank Hit",
                barText1Justify = "LEFT",
                barText1XOffset = 3,
                barText1YOffset = 0,
                barText2Format = "%p",
                barText2Justify = "RIGHT",
                barText2XOffset = -3,
                barText2YOffset = 0,
                countEnabled = false,
                countOperator = "==",
                countValue = 1,
                customText = "",
                decimalThreshold = 1,
                displayType = "bar",
                enabled = true,
                extendTimer = 0,
                id = 5,
                loadRoleDPS = false,
                loadRoleEnabled = true,
                loadRoleHealer = false,
                loadRoleTank = true,
                message = "",
                messageOperator = "find",
                name = "B4 Tank Hit",
                remainingEnabled = true,
                remainingOperator = "<=",
                remainingValue = 5,
                showDecimals = true,
                spellId = "472662",
                textColor = {
                    1,
                    1,
                    1,
                    1,
                },
                textFormat = "%n » %p",
                textJustify = "LEFT",
                triggerType = "timer",
                useBigWigsColors = false,
            },
        },
    },

}